"use client";

import { useRef, useState } from "react";
import QueryInput from "@/pages/Home/components/QueryInput";
import AnswerCard from "@/pages/Home/components/AnswerCard";
import LoadingSkeleton from "@/pages/Home/components/LoadingSkeleton";
import ErrorMessage from "@/pages/Home/components/ErrorMessage";
import { useAsk } from "@/hooks/useAsk";
import { type AskResponse } from "@/services/api";
import {
  Page,
  Inner,
  Header,
  Eyebrow,
  Title,
  Subtitle,
  InputSection,
  ResultSection,
  HistoryList,
  HistoryLabel,
} from "./styles";

type HistoryItem = AskResponse & { query: string; id: number };

export default function Home() {
  const { mutate, isPending, error } = useAsk();
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const nextId = useRef(0);

  function handleSubmit(query: string) {
    mutate(query, {
      onSuccess(data) {
        setHistory((prev) => [{ ...data, query, id: ++nextId.current }, ...prev]);
      },
    });
  }

  return (
    <Page>
      <Inner>
        <Header>
          <Eyebrow>Structured Output</Eyebrow>
          <Title>Ask anything.</Title>
          <Subtitle>
            Objective answers with a confidence score, generated by AI with
            structured JSON output.
          </Subtitle>
        </Header>

        <InputSection>
          <QueryInput onSubmit={handleSubmit} isLoading={isPending} />
        </InputSection>

        <ResultSection>
          {isPending && <LoadingSkeleton />}
          {error && !isPending && <ErrorMessage message={error.message} />}
          {history.length > 0 && !isPending && (
            <>
              {history.length > 1 && <HistoryLabel>History</HistoryLabel>}
              <HistoryList>
                {history.map((item) => (
                  <AnswerCard
                    key={item.id}
                    query={item.query}
                    summary={item.summary}
                    confidence={item.confidence}
                  />
                ))}
              </HistoryList>
            </>
          )}
        </ResultSection>
      </Inner>
    </Page>
  );
}
